### ISSUE TITLE
[BUG] При отправке заявки, на почту пользователя приходит письмо для пользователя и письмо для админа

### ISSUE THREAD

**Issue by kultmet** [antaliadom-team/backend#164]
Опишите баг
Фронт отправляет поля category, location, proprty_type, rooms как список int: [1,2,3]. На почту приходят письма  для автора заявки и для администратора

Как воспроизвести
Шаги для воспроизведения неправильного поведения приложения:

Пройти на URL '/api/objects/order/'
Отправить POST запрос с таким телом:

   {
  "first_name": "tester",
  "last_name": "test",
  "phone": "+7987600000",
  "email": "tester@fake.mail",
  "category": [1, 2],
  "location": [1],
  "property_type": [],
  "agreement": true,
  "rooms": [1, 2]
}
Получить сообщения которое предназначено пользователю и админу  на пользовательский email
```
Здравствуйте, tester. Ваша заявка была принята в работу, скоро с вами свяжется сотрудник нашего агентства.
и т д
```
```
'Поступила заявка от {first_name} {last_name}.\n\n'
```
Ожидаемое поведение
Пользователь получает свое письмо, а админ свое.

Скриншоты

![Image](https://user-images.githubusercontent.com/106805129/225161253-263f311f-897b-4b03-8a28-192eddbff975.png)

Окружение (пожалуйста, заполните информацию):
OS: [например: iOS]
Браузер [например: chrome, safari]
Версия [например: 22]
Дополнительная информация
Добавьте любую информацию касательно проблемы.

**Comment by spaut33** [comment]
Это не баг. Ты получаешь второе письмо, потому что ты админ, твоя учетка с твоим емейлом админская. Отправь заявку с другим адресом, либо сними флаг админа для своего емейла.
