### ISSUE TITLE
Изменить фразу для письма админам

### ISSUE THREAD

**Issue by spaut33** [antaliadom-team/backend#50]
Сейчас получается админы будут получать сообщение, что поступила заявка от админа?
`EMAIL_ADMIN_MESSAGE = 'Поступила заявка от {admin_full_name}.'`
По идее здесь должен быть тоже юзер `{user_full_name}`.

**Comment by pencool** [comment]
Ок, все поправлю. За выходные разберусь со принтом и переделаю.

**Comment by spaut33** [comment]
👍😉
